# Configuration of Tigera Fortimanager Integration Controller
kind: ConfigMap
apiVersion: v1
metadata:
  name: tigera-fortimanager-controller-configs
  namespace: tigera-firewall-controller
data:
  # must have fortigate section even if you don't use FG
  tigera.firewall.fortigate: |-
    # - name: fortigate
    #   ip: 10.99.1.X   ####### UPDATE with FortiGate Private IP
    #   apikey:
    #     secretKeyRef:
    #       name: fortigate
    #       key: fortigate-key
  tigera.firewall.fortimanager-policies: |
    - name: fortimgr
      ip: 10.99.1.X   ####### UPDATE with FortiManager Private IP
      username: tigera_ew_fortimanager_admin
      adom: root
      packagename: calico-ew
      tier: fortimanager
      password:
        secretKeyRef:
          name: fortimgr-ew
          key: fortimgr-pwd