apiVersion: projectcalico.org/v3
kind: Tier
metadata:
  name: fortimanager
spec:
  order: 900
---
apiVersion: projectcalico.org/v3
kind: Tier
metadata:
  name: fortigate
spec:
  order: 800
---
apiVersion: projectcalico.org/v3
kind: Tier
metadata:
  name: platform
spec:
  order: 700
---
apiVersion: projectcalico.org/v3
kind: Tier
metadata:
  name: security
spec:
  order: 500
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: fortigate.pass
spec:
  tier: fortigate
  order: 300
  selector: ''
  ingress:
    - action: Pass
  egress:
    - action: Pass
  types:
    - Ingress
    - Egress
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: fortimanager.pass
spec:
  tier: fortimanager
  order: 300
  selector: ''
  ingress:
    - action: Pass
  egress:
    - action: Pass
  types:
    - Ingress
    - Egress
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: platform.pass
spec:
  tier: platform
  order: 300
  selector: ''
  ingress:
    - action: Pass
  egress:
    - action: Pass
  types:
    - Ingress
    - Egress
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: security.pass
spec:
  tier: security
  order: 300
  selector: ''
  ingress:
    - action: Pass
  egress:
    - action: Pass
  types:
    - Ingress
    - Egress
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: fortigate.app-0-policy
spec:
  tier: fortigate
  selector: app == "app-0"
  egress:
    - action: Allow
      source: {}
      destination: {}
  types:
    - Egress
